apiVersion: v1
kind: Service
metadata:
  name: auth
spec: 
  selector:
    app: auth
  ports:
    - port: 4000
      targetPort: 4000

---

apiVersion: v1
kind: Service
metadata:
  name: todo
spec:
  selector:
    app: todo
  ports:
    - port: 5000
      targetPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: notification
spec:
  selector:
    app: notification
  ports:
    - port: 6000
      targetPort: 6000

---

apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
  type: NodePort